version: '3.8'

services:
  unitofworkdemo1:
    image: unitofworkdemo1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    volumes:
      - .:/app
