version: '3.8'

services:
  unitofworkdemo1:
    image: unitofworkdemo1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__WriterConnection=Server=db;Database=UnitOfWorkDemo;User=sa;Password=Your_password123;Encrypt=false;TrustServerCertificate=true
      - ConnectionStrings__ReaderConnection=Server=db;Database=UnitOfWorkDemoReader;User=sa;Password=Your_password123;Encrypt=false;TrustServerCertificate=true
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
